name = "sapphire-discord-bot"
main = "build/index.js"
compatibility_date = "2026-08-25"

[build]
command = "cargo install -q \"worker-build@^0.8\" && worker-build --release --panic-unwind"

[triggers]
crons = [
    "*/20 13-23,0-6 * * *", # message collection every 20 mins in daylight hours
    "0 7,9,11 * * *", # message collection every 2 hours at night 
    "0 */6 * * *", # send markovs every 6 hours
    "0 */12 * * *", # prune every 12 hours
    # "* * * * *", # send markovs every minute
]

[observability]
enabled = true
head_sampling_rate = 1

[[d1_databases]]
binding = "sapphire_messages"
database_name = "sapphire-messages"
database_id = "3690e4c3-bad6-4329-9b24-e0b0a15f0ebf"
